#device: &device cpu
debug: False
no_cuda: False
gpu: 1

log_tasks: True
log_tasks_interval: 300

plot_inner_loop_loss: True
plot_inner_loop_interval: 250

image_size: 224  # size of input image
save_weight_interval: 300  # will only save weights every n iterations

loss_coef:  # coefficients for losses
  clf_loss: 5.0
  reg_loss: 5.0
  trip_loss: 1.0

mean:
  r: 0
  g: 0
  b: 0
std:
  r: 1
  g: 1
  b: 1

#mean:
#  r: 0.485
#  g: 0.456
#  b: 0.406
#std:
#  r: 0.229
#  g: 0.224
#  b: 0.225

#mean:
#  r: 100
#  g: 100
#  b: 100
#std:
#  r: 50
#  g: 50
#  b: 50

batch_size: 32  # batch size for both validation and train dataloader
num_workers_train: 0  # param for training dataloader
num_workers_val: 0  # param for validation dataloader
log_dir: "logs/oulu/5-shot/protocol_1/"
max_epochs: 30

# meta-learning hyperparameters
ways: 2
shots: 5
tasks_per_step: 4
fast_adaption_steps: 5
iterations: 20000
lr: 0.0001
maml_lr: 0.0001
seed: 1
no_adaptation: False

train_df: "/root/datasets/oulu/protocol2_train.csv"
val_df: "/root/datasets/oulu/protocol2_val.csv"
train_bookkeeping_path: "datasets/bookkeeping_oulu_protocol2_train"
val_bookkeeping_path: "datasets/bookkeeping_oulu_protocol2_val"

# deprecated
dataset_root: "/root/datasets/oulu"
