#device: &device cpu
debug: False
no_cuda: False
gpu: 0

show_imgs: False

image_size: 224  # size of input image
save_weight_interval: 100  # will only save weights every n iterations

#mean:
#  r: 0
#  g: 0
#  b: 0
#std:
#  r: 1
#  g: 1
#  b: 1

mean:
  r: 0.485
  g: 0.456
  b: 0.406
std:
  r: 0.229
  g: 0.224
  b: 0.225

batch_size: 32  # batch size for both validation and train dataloader
num_workers_train: 0  # param for training dataloader
num_workers_val: 0  # param for validation dataloader
log_dir: "logs/oulu/5-shot/"
max_epochs: 30

# meta-learning hyperparameters
ways: 2
shots: 5
tasks_per_step: 2
fast_adaption_steps: 5
iterations: 10000
lr: 0.005
maml_lr: 0.001
seed: 1

train_df: "/root/datasets/oulu/train.csv"
dataset_root: "/root/datasets/oulu"
indices_to_labels: "datasets/indices_to_labels"
bookkeeping_path: "datasets/bookkeeping_oulu"
